CREATE TABLE users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	phone TEXT NOT NULL UNIQUE,
	login TEXT NOT NULL UNIQUE, 
	password TEXT NOT NULL, 
	name TEXT NOT NULL, 
	birth DATE NOT NULL, 
	tg TEXT UNIQUE, 
	email TEXT UNIQUE
);